### ISSUE TITLE
`\WP_Mock\Tools\TestCase::mockStaticMethod` broken with recent Patchwork versions

### ISSUE THREAD

**Issue by creativecoder** [10up/wp_mock#116]
Using `$this->mockStaticMethod` is not working using wp_mock v0.3.0 and patchwork v2.1.7.

After specifying `WP_Mock::setUsePatchwork( true );`, I still receive the error `Exception: Patchwork is not loaded! Please load patchwork before mocking static methods!`

This can be traced to https://github.com/10up/wp_mock/blob/master/php/WP_Mock/Tools/TestCase.php#L167, because `Patchwork\Interceptor\patch` is not a function.

I can get it working by doing the following:

1. Remove the check for `Patchwork\Interceptor\patch` on https://github.com/10up/wp_mock/blob/master/php/WP_Mock/Tools/TestCase.php#L167

2. Change to call to `\Patchwork\redefine` in https://github.com/10up/wp_mock/blob/master/php/WP_Mock/Tools/TestCase.php#L197 from
```php
\Patchwork\redefine( "$class::$method", function () use ( $mock, $safe_method ) {
    return call_user_func_array( array( $mock, $safe_method ), func_get_args() );
}, ! ( $rMethod ) );
```
to
```php
\Patchwork\redefine( "$class::$method", function () use ( $mock, $safe_method ) {
   return call_user_func_array( array( $mock, $safe_method ), func_get_args() );
});
```

**Comment by robynm** [comment]
I have run into this as well. Any updates?

**Comment by ericmann** [comment]
No updates on this issue directly, but we've updated the tool since then and no one else has reported things ... so closing this unless you're still seeing it.
